// <autogenerated/>
namespace GitLab.Lib;

public class CreatedBy
{
    public string displayName { get; set; }

    public string url { get; set; }

    public Links _links { get; set; }

    public string id { get; set; }

    public string uniqueName { get; set; }

    public string imageUrl { get; set; }

    public string descriptor { get; set; }
}

public class LastMergeSourceCommit
{
    public string commitId { get; set; }

    public string url { get; set; }
}

public class LastMergeTargetCommit
{
    public string commitId { get; set; }

    public string url { get; set; }
}

public class LastMergeCommit
{
    public string commitId { get; set; }

    public string url { get; set; }
}

public class VotedFor
{
    public string reviewerUrl { get; set; }

    public int vote { get; set; }

    public string displayName { get; set; }

    public string url { get; set; }

    public Links _links { get; set; }

    public string id { get; set; }

    public string uniqueName { get; set; }

    public string imageUrl { get; set; }

    public bool isContainer { get; set; }
}

public class Reviewer
{
    public string reviewerUrl { get; set; }

    public int vote { get; set; }

    public bool hasDeclined { get; set; }

    public bool isFlagged { get; set; }

    public string displayName { get; set; }

    public string url { get; set; }

    public Links _links { get; set; }

    public string id { get; set; }

    public string uniqueName { get; set; }

    public string imageUrl { get; set; }

    public bool? isRequired { get; set; }

    public bool? isContainer { get; set; }

    public List<VotedFor> votedFor { get; set; }
}

public class CompletionOptions
{
    public string mergeStrategy { get; set; }

    public List<int> autoCompleteIgnoreConfigIds { get; set; }

    public string mergeCommitMessage { get; set; }

    public bool? deleteSourceBranch { get; set; }

    public bool? squashMerge { get; set; }

    public bool? transitionWorkItems { get; set; }
}

public class AutoCompleteSetBy
{
    public string displayName { get; set; }

    public string url { get; set; }

    public Links _links { get; set; }

    public string id { get; set; }

    public string uniqueName { get; set; }

    public string imageUrl { get; set; }

    public string descriptor { get; set; }
}

public class PullRequest
{
    public Repository repository { get; set; }

    public int pullRequestId { get; set; }

    public int codeReviewId { get; set; }

    public string status { get; set; }

    public CreatedBy createdBy { get; set; }

    public DateTime creationDate { get; set; }
    public DateTime closedDate { get; set; }
    public string title { get; set; }

    public string description { get; set; }

    public string sourceRefName { get; set; }

    public string targetRefName { get; set; }

    public string mergeStatus { get; set; }

    public bool isDraft { get; set; }

    public string mergeId { get; set; }

    public LastMergeSourceCommit lastMergeSourceCommit { get; set; }

    public LastMergeTargetCommit lastMergeTargetCommit { get; set; }

    public LastMergeCommit lastMergeCommit { get; set; }

    public List<Reviewer> reviewers { get; set; }

    public string url { get; set; }

    public CompletionOptions completionOptions { get; set; }

    public bool supportsIterations { get; set; }
    public DateTime completionQueueTime { get; set; }

    public AutoCompleteSetBy autoCompleteSetBy { get; set; }
}

public class PullRequests
{
    public List<PullRequest> value { get; set; }

    public int count { get; set; }
}
