// <autogenerated/>
namespace GitLab.Lib;

public class Avatar
{
    public string href { get; set; }
}

public class PushedBy
{
    public string displayName { get; set; }
    public string url { get; set; }
    public Links _links { get; set; }
    public string id { get; set; }
    public string uniqueName { get; set; }
    public string imageUrl { get; set; }
    public string descriptor { get; set; }
}

public class Push
{
    public Repository repository { get; set; }
    public PushedBy pushedBy { get; set; }
    public int pushId { get; set; }
    public DateTime date { get; set; }
    public string url { get; set; }

    // Adding in branch for reporting
    public string branch { get; set; }
}

public class Pushes
{
    public int count { get; set; }
    public List<Push> value { get; set; }
}